name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for contributing to make this project better😎  Keep up and follow to solve this issue.  You are welcome to draft a pull request here at https://github.com/TermuxArch/TermuxArch/pulls too in order to resolve this issue by tapping "new" at the link provided.  Do not worry if it is not perfect on the first try, that is what pull requests are for, in order to improve the code.'        pr-message: 'Thank you for contributing to make this project better🎉'
